/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package test.avroparquet;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Distribution extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Distribution\",\"namespace\":\"test.avroparquet\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"transaction_id\",\"type\":[\"int\",\"null\"]},{\"name\":\"sender\",\"type\":\"string\"},{\"name\":\"abonent\",\"type\":\"string\"},{\"name\":\"sms_text\",\"type\":[\"string\",\"null\"]},{\"name\":\"add_date\",\"type\":[\"long\",\"null\"]},{\"name\":\"send_date\",\"type\":[\"long\",\"null\"]},{\"name\":\"delivery_date\",\"type\":[\"long\",\"null\"]},{\"name\":\"pending_count\",\"type\":\"int\"},{\"name\":\"accepted_count\",\"type\":\"int\"},{\"name\":\"delivered_count\",\"type\":\"int\"},{\"name\":\"rejected_count\",\"type\":\"int\"},{\"name\":\"error\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public java.lang.Integer transaction_id;
  @Deprecated public java.lang.CharSequence sender;
  @Deprecated public java.lang.CharSequence abonent;
  @Deprecated public java.lang.CharSequence sms_text;
  @Deprecated public java.lang.Long add_date;
  @Deprecated public java.lang.Long send_date;
  @Deprecated public java.lang.Long delivery_date;
  @Deprecated public int pending_count;
  @Deprecated public int accepted_count;
  @Deprecated public int delivered_count;
  @Deprecated public int rejected_count;
  @Deprecated public java.lang.CharSequence error;

  /**
   * Default constructor.
   */
  public Distribution() {}

  /**
   * All-args constructor.
   */
  public Distribution(java.lang.Integer id, java.lang.Integer transaction_id, java.lang.CharSequence sender, java.lang.CharSequence abonent, java.lang.CharSequence sms_text, java.lang.Long add_date, java.lang.Long send_date, java.lang.Long delivery_date, java.lang.Integer pending_count, java.lang.Integer accepted_count, java.lang.Integer delivered_count, java.lang.Integer rejected_count, java.lang.CharSequence error) {
    this.id = id;
    this.transaction_id = transaction_id;
    this.sender = sender;
    this.abonent = abonent;
    this.sms_text = sms_text;
    this.add_date = add_date;
    this.send_date = send_date;
    this.delivery_date = delivery_date;
    this.pending_count = pending_count;
    this.accepted_count = accepted_count;
    this.delivered_count = delivered_count;
    this.rejected_count = rejected_count;
    this.error = error;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return transaction_id;
    case 2: return sender;
    case 3: return abonent;
    case 4: return sms_text;
    case 5: return add_date;
    case 6: return send_date;
    case 7: return delivery_date;
    case 8: return pending_count;
    case 9: return accepted_count;
    case 10: return delivered_count;
    case 11: return rejected_count;
    case 12: return error;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: transaction_id = (java.lang.Integer)value$; break;
    case 2: sender = (java.lang.CharSequence)value$; break;
    case 3: abonent = (java.lang.CharSequence)value$; break;
    case 4: sms_text = (java.lang.CharSequence)value$; break;
    case 5: add_date = (java.lang.Long)value$; break;
    case 6: send_date = (java.lang.Long)value$; break;
    case 7: delivery_date = (java.lang.Long)value$; break;
    case 8: pending_count = (java.lang.Integer)value$; break;
    case 9: accepted_count = (java.lang.Integer)value$; break;
    case 10: delivered_count = (java.lang.Integer)value$; break;
    case 11: rejected_count = (java.lang.Integer)value$; break;
    case 12: error = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'transaction_id' field.
   */
  public java.lang.Integer getTransactionId() {
    return transaction_id;
  }

  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.Integer value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'sender' field.
   */
  public java.lang.CharSequence getSender() {
    return sender;
  }

  /**
   * Sets the value of the 'sender' field.
   * @param value the value to set.
   */
  public void setSender(java.lang.CharSequence value) {
    this.sender = value;
  }

  /**
   * Gets the value of the 'abonent' field.
   */
  public java.lang.CharSequence getAbonent() {
    return abonent;
  }

  /**
   * Sets the value of the 'abonent' field.
   * @param value the value to set.
   */
  public void setAbonent(java.lang.CharSequence value) {
    this.abonent = value;
  }

  /**
   * Gets the value of the 'sms_text' field.
   */
  public java.lang.CharSequence getSmsText() {
    return sms_text;
  }

  /**
   * Sets the value of the 'sms_text' field.
   * @param value the value to set.
   */
  public void setSmsText(java.lang.CharSequence value) {
    this.sms_text = value;
  }

  /**
   * Gets the value of the 'add_date' field.
   */
  public java.lang.Long getAddDate() {
    return add_date;
  }

  /**
   * Sets the value of the 'add_date' field.
   * @param value the value to set.
   */
  public void setAddDate(java.lang.Long value) {
    this.add_date = value;
  }

  /**
   * Gets the value of the 'send_date' field.
   */
  public java.lang.Long getSendDate() {
    return send_date;
  }

  /**
   * Sets the value of the 'send_date' field.
   * @param value the value to set.
   */
  public void setSendDate(java.lang.Long value) {
    this.send_date = value;
  }

  /**
   * Gets the value of the 'delivery_date' field.
   */
  public java.lang.Long getDeliveryDate() {
    return delivery_date;
  }

  /**
   * Sets the value of the 'delivery_date' field.
   * @param value the value to set.
   */
  public void setDeliveryDate(java.lang.Long value) {
    this.delivery_date = value;
  }

  /**
   * Gets the value of the 'pending_count' field.
   */
  public java.lang.Integer getPendingCount() {
    return pending_count;
  }

  /**
   * Sets the value of the 'pending_count' field.
   * @param value the value to set.
   */
  public void setPendingCount(java.lang.Integer value) {
    this.pending_count = value;
  }

  /**
   * Gets the value of the 'accepted_count' field.
   */
  public java.lang.Integer getAcceptedCount() {
    return accepted_count;
  }

  /**
   * Sets the value of the 'accepted_count' field.
   * @param value the value to set.
   */
  public void setAcceptedCount(java.lang.Integer value) {
    this.accepted_count = value;
  }

  /**
   * Gets the value of the 'delivered_count' field.
   */
  public java.lang.Integer getDeliveredCount() {
    return delivered_count;
  }

  /**
   * Sets the value of the 'delivered_count' field.
   * @param value the value to set.
   */
  public void setDeliveredCount(java.lang.Integer value) {
    this.delivered_count = value;
  }

  /**
   * Gets the value of the 'rejected_count' field.
   */
  public java.lang.Integer getRejectedCount() {
    return rejected_count;
  }

  /**
   * Sets the value of the 'rejected_count' field.
   * @param value the value to set.
   */
  public void setRejectedCount(java.lang.Integer value) {
    this.rejected_count = value;
  }

  /**
   * Gets the value of the 'error' field.
   */
  public java.lang.CharSequence getError() {
    return error;
  }

  /**
   * Sets the value of the 'error' field.
   * @param value the value to set.
   */
  public void setError(java.lang.CharSequence value) {
    this.error = value;
  }

  /** Creates a new Distribution RecordBuilder */
  public static test.avroparquet.Distribution.Builder newBuilder() {
    return new test.avroparquet.Distribution.Builder();
  }
  
  /** Creates a new Distribution RecordBuilder by copying an existing Builder */
  public static test.avroparquet.Distribution.Builder newBuilder(test.avroparquet.Distribution.Builder other) {
    return new test.avroparquet.Distribution.Builder(other);
  }
  
  /** Creates a new Distribution RecordBuilder by copying an existing Distribution instance */
  public static test.avroparquet.Distribution.Builder newBuilder(test.avroparquet.Distribution other) {
    return new test.avroparquet.Distribution.Builder(other);
  }
  
  /**
   * RecordBuilder for Distribution instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Distribution>
    implements org.apache.avro.data.RecordBuilder<Distribution> {

    private int id;
    private java.lang.Integer transaction_id;
    private java.lang.CharSequence sender;
    private java.lang.CharSequence abonent;
    private java.lang.CharSequence sms_text;
    private java.lang.Long add_date;
    private java.lang.Long send_date;
    private java.lang.Long delivery_date;
    private int pending_count;
    private int accepted_count;
    private int delivered_count;
    private int rejected_count;
    private java.lang.CharSequence error;

    /** Creates a new Builder */
    private Builder() {
      super(test.avroparquet.Distribution.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(test.avroparquet.Distribution.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Distribution instance */
    private Builder(test.avroparquet.Distribution other) {
            super(test.avroparquet.Distribution.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[1].schema(), other.transaction_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sender)) {
        this.sender = data().deepCopy(fields()[2].schema(), other.sender);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.abonent)) {
        this.abonent = data().deepCopy(fields()[3].schema(), other.abonent);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sms_text)) {
        this.sms_text = data().deepCopy(fields()[4].schema(), other.sms_text);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.add_date)) {
        this.add_date = data().deepCopy(fields()[5].schema(), other.add_date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.send_date)) {
        this.send_date = data().deepCopy(fields()[6].schema(), other.send_date);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.delivery_date)) {
        this.delivery_date = data().deepCopy(fields()[7].schema(), other.delivery_date);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.pending_count)) {
        this.pending_count = data().deepCopy(fields()[8].schema(), other.pending_count);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.accepted_count)) {
        this.accepted_count = data().deepCopy(fields()[9].schema(), other.accepted_count);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.delivered_count)) {
        this.delivered_count = data().deepCopy(fields()[10].schema(), other.delivered_count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.rejected_count)) {
        this.rejected_count = data().deepCopy(fields()[11].schema(), other.rejected_count);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.error)) {
        this.error = data().deepCopy(fields()[12].schema(), other.error);
        fieldSetFlags()[12] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public test.avroparquet.Distribution.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public test.avroparquet.Distribution.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'transaction_id' field */
    public java.lang.Integer getTransactionId() {
      return transaction_id;
    }
    
    /** Sets the value of the 'transaction_id' field */
    public test.avroparquet.Distribution.Builder setTransactionId(java.lang.Integer value) {
      validate(fields()[1], value);
      this.transaction_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'transaction_id' field has been set */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'transaction_id' field */
    public test.avroparquet.Distribution.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'sender' field */
    public java.lang.CharSequence getSender() {
      return sender;
    }
    
    /** Sets the value of the 'sender' field */
    public test.avroparquet.Distribution.Builder setSender(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.sender = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'sender' field has been set */
    public boolean hasSender() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'sender' field */
    public test.avroparquet.Distribution.Builder clearSender() {
      sender = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'abonent' field */
    public java.lang.CharSequence getAbonent() {
      return abonent;
    }
    
    /** Sets the value of the 'abonent' field */
    public test.avroparquet.Distribution.Builder setAbonent(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.abonent = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'abonent' field has been set */
    public boolean hasAbonent() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'abonent' field */
    public test.avroparquet.Distribution.Builder clearAbonent() {
      abonent = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'sms_text' field */
    public java.lang.CharSequence getSmsText() {
      return sms_text;
    }
    
    /** Sets the value of the 'sms_text' field */
    public test.avroparquet.Distribution.Builder setSmsText(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.sms_text = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'sms_text' field has been set */
    public boolean hasSmsText() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'sms_text' field */
    public test.avroparquet.Distribution.Builder clearSmsText() {
      sms_text = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'add_date' field */
    public java.lang.Long getAddDate() {
      return add_date;
    }
    
    /** Sets the value of the 'add_date' field */
    public test.avroparquet.Distribution.Builder setAddDate(java.lang.Long value) {
      validate(fields()[5], value);
      this.add_date = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'add_date' field has been set */
    public boolean hasAddDate() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'add_date' field */
    public test.avroparquet.Distribution.Builder clearAddDate() {
      add_date = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'send_date' field */
    public java.lang.Long getSendDate() {
      return send_date;
    }
    
    /** Sets the value of the 'send_date' field */
    public test.avroparquet.Distribution.Builder setSendDate(java.lang.Long value) {
      validate(fields()[6], value);
      this.send_date = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'send_date' field has been set */
    public boolean hasSendDate() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'send_date' field */
    public test.avroparquet.Distribution.Builder clearSendDate() {
      send_date = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'delivery_date' field */
    public java.lang.Long getDeliveryDate() {
      return delivery_date;
    }
    
    /** Sets the value of the 'delivery_date' field */
    public test.avroparquet.Distribution.Builder setDeliveryDate(java.lang.Long value) {
      validate(fields()[7], value);
      this.delivery_date = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'delivery_date' field has been set */
    public boolean hasDeliveryDate() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'delivery_date' field */
    public test.avroparquet.Distribution.Builder clearDeliveryDate() {
      delivery_date = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'pending_count' field */
    public java.lang.Integer getPendingCount() {
      return pending_count;
    }
    
    /** Sets the value of the 'pending_count' field */
    public test.avroparquet.Distribution.Builder setPendingCount(int value) {
      validate(fields()[8], value);
      this.pending_count = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'pending_count' field has been set */
    public boolean hasPendingCount() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'pending_count' field */
    public test.avroparquet.Distribution.Builder clearPendingCount() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'accepted_count' field */
    public java.lang.Integer getAcceptedCount() {
      return accepted_count;
    }
    
    /** Sets the value of the 'accepted_count' field */
    public test.avroparquet.Distribution.Builder setAcceptedCount(int value) {
      validate(fields()[9], value);
      this.accepted_count = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'accepted_count' field has been set */
    public boolean hasAcceptedCount() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'accepted_count' field */
    public test.avroparquet.Distribution.Builder clearAcceptedCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'delivered_count' field */
    public java.lang.Integer getDeliveredCount() {
      return delivered_count;
    }
    
    /** Sets the value of the 'delivered_count' field */
    public test.avroparquet.Distribution.Builder setDeliveredCount(int value) {
      validate(fields()[10], value);
      this.delivered_count = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'delivered_count' field has been set */
    public boolean hasDeliveredCount() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'delivered_count' field */
    public test.avroparquet.Distribution.Builder clearDeliveredCount() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'rejected_count' field */
    public java.lang.Integer getRejectedCount() {
      return rejected_count;
    }
    
    /** Sets the value of the 'rejected_count' field */
    public test.avroparquet.Distribution.Builder setRejectedCount(int value) {
      validate(fields()[11], value);
      this.rejected_count = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'rejected_count' field has been set */
    public boolean hasRejectedCount() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'rejected_count' field */
    public test.avroparquet.Distribution.Builder clearRejectedCount() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'error' field */
    public java.lang.CharSequence getError() {
      return error;
    }
    
    /** Sets the value of the 'error' field */
    public test.avroparquet.Distribution.Builder setError(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.error = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'error' field has been set */
    public boolean hasError() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'error' field */
    public test.avroparquet.Distribution.Builder clearError() {
      error = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    public Distribution build() {
      try {
        Distribution record = new Distribution();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.transaction_id = fieldSetFlags()[1] ? this.transaction_id : (java.lang.Integer) defaultValue(fields()[1]);
        record.sender = fieldSetFlags()[2] ? this.sender : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.abonent = fieldSetFlags()[3] ? this.abonent : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.sms_text = fieldSetFlags()[4] ? this.sms_text : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.add_date = fieldSetFlags()[5] ? this.add_date : (java.lang.Long) defaultValue(fields()[5]);
        record.send_date = fieldSetFlags()[6] ? this.send_date : (java.lang.Long) defaultValue(fields()[6]);
        record.delivery_date = fieldSetFlags()[7] ? this.delivery_date : (java.lang.Long) defaultValue(fields()[7]);
        record.pending_count = fieldSetFlags()[8] ? this.pending_count : (java.lang.Integer) defaultValue(fields()[8]);
        record.accepted_count = fieldSetFlags()[9] ? this.accepted_count : (java.lang.Integer) defaultValue(fields()[9]);
        record.delivered_count = fieldSetFlags()[10] ? this.delivered_count : (java.lang.Integer) defaultValue(fields()[10]);
        record.rejected_count = fieldSetFlags()[11] ? this.rejected_count : (java.lang.Integer) defaultValue(fields()[11]);
        record.error = fieldSetFlags()[12] ? this.error : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
